skanmotutgaaende.endpointuri=sftp://${skanmotutgaaende.sftp.host}:${skanmotutgaaende.sftp.port}
skanmotutgaaende.endpointconfig=username=${skanmotutgaaende.sftp.username}\
  &password=&preferredAuthentications=publickey\
  &privateKeyFile=${skanmotutgaaende.sftp.privateKey}\
  &strictHostKeyChecking=yes&knownHostsFile=${skanmotutgaaende.sftp.hostKey}\
  &binary=true