skanmotutgaaende.endpointuri=sftp://{{skanmotutgaaende.sftp.host}}:{{skanmotutgaaende.sftp.port}}
skanmotutgaaende.endpointconfig=username={{skanmotutgaaende.sftp.username}}\
  &***passord=gammelt_passord***\
  &privateKeyFile={{skanmotutgaaende.sftp.privateKey}}\
  &strictHostKeyChecking=yes&knownHostsFile={{skanmotutgaaende.sftp.hostKey}}\
  &binary=true