spring.main.banner-mode=off
logging.config=classpath:logback-spring.xml

skanmotutgaaende.filomraade.inngaaendemappe=inbound/SKANMOTUTGAAENDE
skanmotutgaaende.filomraade.feilmappe=inbound/SKANMOTUTGAAENDE_FEIL

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus