spring.main.banner-mode=off
logging.config=classpath:logback-spring.xml

server.shutdown=graceful
camel.springboot.use-mdc-logging=true
camel.springboot.jmx-enabled=false

skanmotutgaaende.filomraade.inngaaendemappe=inbound/SKANMOTUTGAAENDE
skanmotutgaaende.filomraade.feilmappe=inbound/SKANMOTUTGAAENDE_FEIL
skanmotutgaaende.filomraade.feilmappezip=inbound/SKANMOTUTGAAENDE_FEILET
skanmotutgaaende.completiontimeout=30s

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus