spring.main.banner-mode=off
logging.config=classpath:logback-spring.xml

skanmotutgaaende.filomraade.inngaaendemappe=/inbound/SKANMOTUTGAAENDE
skanmotutgaaende.filomraade.feilmappe=/inbound/SKANMOTUTGAAENDE_FEIL
skanmotutgaaende.filomraade.utgaaendemappe=/outbound/SKANMOTUTGAAENDE