kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: skanmotutgaaende
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SKANMOTUTGAAENDE_DOKARKIVJOURNALPOSTURL
      value: {{ SKANMOTUTGAAENDE_DOKARKIVJOURNALPOSTURL }}
    - name: SKANMOTUTGAAENDE_SFTP_PRIVATEKEY
      value: /var/run/secrets/nais.io/keys/privatekey
    - name: SKANMOTUTGAAENDE_SFTP_HOSTKEY
      value: /var/run/secrets/nais.io/keys/hostkey
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVSKANMOTUTGAAENDE }}
        mountPath: /var/run/secrets/nais.io/srvskanmotutgaaende
      - kvPath: {{ SKANMOTUTGAAENDE_VAULT }}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: {{ SFTP_KEYS }}
        mountPath: /var/run/secrets/nais.io/vault
